[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[net]
git-fetch-with-cli = true

[patch."ssh://git@github.com/edgeimpulse/edge-impulse-runner-rs.git"]
edge_impulse_runner = { path = "../edge-impulse-runner-rs" }